version: '3.9'

services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monkeypox-api
    ports:
      - "8000:3000"
    networks:
      - app-network
    volumes:
      - ./monkeypox-api/:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env

  db:
    restart: always
    image: postgres:latest
    container_name: monkeypox-db
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD=kataku
    ports:
      - 54321:5432
    env_file:
      - .env
    expose:
      - 5432
    networks:
      - app-network

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:${NGINX_PORT}
    depends_on:
      - webapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: monkeypox-adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - app-network

volumes:
  postgres:
    driver: local

networks:
  app-network:
    driver: bridge